### ISSUE TITLE
Bug on gookbap command

### ISSUE THREAD

**Issue by wonderlandpark** [cotwo0139/CHINOBOT_BETA#47]
![image](https://user-images.githubusercontent.com/31924512/74546488-f48bb100-4f8d-11ea-95f6-f5a8eb0506ea.png)

Bug when I type Not number

**Comment by cotwo0139** [comment]
재미삼아 잠시 만든 기능입니다, 곧 지워질 기능입니다. 이 명령어는 버그 관련 이슈를 받지 않습니다.
